Repository Moongeul/Backend, pull requests merged in 2024-08, with the labels that each got.

#13 [SETTING] H2 -> Mysql 로 변경
  build.gradle
Labels: SETTING, 태근

#15 [FEAT] 카카오 OAuth2.0 구현
  build.gradle
  src/main/java/com/core/book/api/member/controller/MemberController.java
  src/main/java/com/core/book/api/member/entity/Member.java
  src/main/java/com/core/book/api/member/entity/Role.java
  src/main/java/com/core/book/api/member/jwt/filter/JwtAuthenticationProcessingFilter.java
  src/main/java/com/core/book/api/member/jwt/service/JwtService.java
  src/main/java/com/core/book/api/member/jwt/util/PasswordUtil.java
  src/main/java/com/core/book/api/member/oauth2/CustomOAuth2User.java
  src/main/java/com/core/book/api/member/oauth2/OAuthAttributes.java
  src/main/java/com/core/book/api/member/oauth2/handler/OAuth2LoginFailureHandler.java
  src/main/java/com/core/book/api/member/oauth2/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/core/book/api/member/oauth2/userinfo/KakaoOAuth2UserInfo.java
  src/main/java/com/core/book/api/member/oauth2/userinfo/OAuth2UserInfo.java
  src/main/java/com/core/book/api/member/repository/MemberRepository.java
  src/main/java/com/core/book/api/member/service/MemberService.java
  src/main/java/com/core/book/common/config/SecurityConfig.java
  src/main/java/com/core/book/common/config/jwt/JwtConfig.java
  src/main/java/com/core/book/common/config/oauth2/OAuth2Config.java
  src/main/java/com/core/book/common/exception/NotFoundException.java
  src/main/java/com/core/book/common/response/ErrorStatus.java
  src/main/java/com/core/book/common/response/SuccessStatus.java
Labels: FEAT, 태근

#19 [FEAT] 도서 API 데이터 요청 및 저장 기능 구현
  src/main/java/com/core/book/api/book/controller/BookController.java
  src/main/java/com/core/book/api/book/dto/BookDto.java
  src/main/java/com/core/book/api/book/dto/ResultDto.java
  src/main/java/com/core/book/api/book/entity/Book.java
  src/main/java/com/core/book/api/book/repository/BookRepository.java
  src/main/java/com/core/book/api/book/service/BookService.java
  src/main/java/com/core/book/common/response/SuccessStatus.java
Labels: FEAT, 주현

#22 [FIX] 도서 API Response 에러 해결
  src/main/java/com/core/book/api/book/controller/BookController.java
Labels: FIX, 주현

#24 [FIX] 스프링시큐리티 CORS 오류 해결 및 도메인 등록
  src/main/java/com/core/book/common/config/SecurityConfig.java
Labels: FIX, 주현

#26 [FIX] 스프링시큐리티 책 검색 API 토큰인증 해제
  src/main/java/com/core/book/common/config/SecurityConfig.java
Labels: FIX, 태근

#28 [FIX] SwaggerConfig 에서 Base Server URL을 https로 변경
  src/main/java/com/core/book/common/config/swagger/SwaggerConfig.java
Labels: FIX, 태근

#30 [FIX] Swagger 쿠키 인증 기능 구현 및 https 적용
  src/main/java/com/core/book/api/HealthCheckController.java
  src/main/java/com/core/book/common/config/swagger/SwaggerConfig.java
Labels: FIX, 태근

#33 [FIX] 도서 API Swagger 설명 수정
  src/main/java/com/core/book/api/book/controller/BookController.java
Labels: FIX, 주현

#35 [FIX] 도서 API 예외 처리 추가
  src/main/java/com/core/book/api/book/controller/BookController.java
  src/main/java/com/core/book/api/book/service/BookService.java
  src/main/java/com/core/book/api/member/controller/MemberController.java
  src/main/java/com/core/book/common/response/ApiResponse.java
  src/main/java/com/core/book/common/response/ErrorStatus.java
Labels: FIX, 주현

#39 [FEAT] 회원 정보 수정(프로필사진, 닉네임, 정보공개, 탈퇴) 및 조회 기능 구현
  build.gradle
  src/main/java/com/core/book/api/member/controller/MemberController.java
  src/main/java/com/core/book/api/member/dto/InfoOpenRequestDTO.java
  src/main/java/com/core/book/api/member/dto/UserInfoResponseDTO.java
  src/main/java/com/core/book/api/member/entity/InfoOpen.java
  src/main/java/com/core/book/api/member/entity/Member.java
  src/main/java/com/core/book/api/member/jwt/service/JwtService.java
  src/main/java/com/core/book/api/member/repository/InfoOpenRepository.java
  src/main/java/com/core/book/api/member/repository/MemberRepository.java
  src/main/java/com/core/book/api/member/service/MemberService.java
  src/main/java/com/core/book/api/member/service/S3Service.java
  src/main/java/com/core/book/common/config/aws/S3Config.java
  src/main/java/com/core/book/common/exception/InternalServerException.java
  src/main/java/com/core/book/common/response/ErrorStatus.java
  src/main/java/com/core/book/common/response/SuccessStatus.java
Labels: FEAT, 태근
