Repository Moongeul/Backend, pull requests merged in 2024-11, with the labels that each got.

#114 [FEAT] 댓글 등록, 조회, 수정, 삭제 기능 조회 구현
  src/main/java/com/core/book/api/comment/controller/CommentController.java
  src/main/java/com/core/book/api/comment/dto/CommentCreateDTO.java
  src/main/java/com/core/book/api/comment/dto/CommentResponseDTO.java
  src/main/java/com/core/book/api/comment/dto/CommentUpdateDTO.java
  src/main/java/com/core/book/api/comment/entity/Comment.java
  src/main/java/com/core/book/api/comment/repository/CommentRepository.java
  src/main/java/com/core/book/api/comment/service/CommentService.java
  src/main/java/com/core/book/common/response/ErrorStatus.java
  src/main/java/com/core/book/common/response/SuccessStatus.java
Labels: FEAT, 태근

#117 [FIX] 게시글 댓글 수 등록 로직 수정
  src/main/java/com/core/book/api/article/entity/Article.java
  src/main/java/com/core/book/api/article/entity/ReviewArticle.java
  src/main/java/com/core/book/api/comment/service/CommentService.java
Labels: FIX, 태근

#120 [FIX] BaseTimeEntity 중복 SuperBuild 어노테이션 제거
  src/main/java/com/core/book/common/entity/BaseTimeEntity.java
Labels: FIX, 태근

#124 [FIX] 책장 전체 조회 API - 응답에 읽은 책의 id 값 추가하기 & userId 코드 컨벤션 수정
  src/main/java/com/core/book/api/bookshelf/controller/BookshelfController.java
  src/main/java/com/core/book/api/bookshelf/dto/ReadBooksDTO.java
  src/main/java/com/core/book/api/bookshelf/dto/ReadBookshelfResponseDTO.java
  src/main/java/com/core/book/api/bookshelf/dto/WishBooksDTO.java
  src/main/java/com/core/book/api/bookshelf/service/BookShelfService.java
Labels: FIX, 주현

#126 [FIX] 책장 수정/삭제 API - 타 사용자 수정/삭제 예외처리
  src/main/java/com/core/book/api/bookshelf/controller/BookshelfController.java
  src/main/java/com/core/book/api/bookshelf/dto/ReadBooksDTO.java
  src/main/java/com/core/book/api/bookshelf/dto/WishBooksDTO.java
  src/main/java/com/core/book/api/bookshelf/service/BookShelfService.java
  src/main/java/com/core/book/common/response/ErrorStatus.java
Labels: FIX, 주현

#129 [FIX] 읽고 싶은 책 책장 전체 조회 API - 응답에 읽고 싶은 책의 id 값 추가하기
  src/main/java/com/core/book/api/bookshelf/dto/ReadBookshelfResponseDTO.java
  src/main/java/com/core/book/api/bookshelf/dto/WishBookshelfResponseDTO.java
  src/main/java/com/core/book/api/bookshelf/service/BookShelfService.java
Labels: FIX, 주현

#131 [FIX] 읽은 책 책장 API - 책 태그 수정 오류 및 NULL 저장 오류 해결
  src/main/java/com/core/book/api/bookshelf/service/BookShelfService.java
Labels: FIX, 주현
