Repository Moongeul/Backend, pull requests merged in 2024-07, with the labels that each got.

#2 [SETTING] 프로젝트 파일 등록
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/core/book/BookApplication.java
  src/test/java/com/core/book/BookApplicationTests.java
Labels: SETTING, 태근

#4 [SETTING] Dockerfile 생성
  Dockerfile
Labels: SETTING, 주현

#6 [SETTING] 프로젝트 파일 등록
  build.gradle
  src/main/java/com/core/book/BookApplication.java
  src/main/java/com/core/book/api/HealthCheckController.java
  src/main/java/com/core/book/common/advice/ControllerExceptionAdvice.java
  src/main/java/com/core/book/common/entity/BaseTimeEntity.java
  src/main/java/com/core/book/common/exception/BaseException.java
  src/main/java/com/core/book/common/response/ApiResponse.java
  src/main/java/com/core/book/common/response/ErrorStatus.java
  src/main/java/com/core/book/common/response/SuccessStatus.java
Labels: SETTING

#8 [FEAT] health Check API 구현
  src/main/java/com/core/book/api/HealthCheckController.java
Labels: FEAT, 주현

#10 [FIX] JPA H2 임의 설정
  build.gradle
Labels: FIX, 태근
