Repository Moongeul/Backend, pull requests merged in 2024-09, with the labels that each got.

#57 [FIX] 아키텍처 구조 초안 생성
  README.md
Labels: FIX, 태근

#60 [FIX] 로그인 성공 리다이렉트 URL 수정
  build.gradle
  src/main/java/com/core/book/BookApplication.java
  src/main/java/com/core/book/api/member/controller/MemberController.java
  src/main/java/com/core/book/api/member/dto/FollowerUserDTO.java
  src/main/java/com/core/book/api/member/dto/OtherUserInfoResponseDTO.java
  src/main/java/com/core/book/api/member/dto/UserInfoResponseDTO.java
  src/main/java/com/core/book/api/member/oauth2/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/core/book/api/member/service/MemberService.java
  src/main/java/com/core/book/common/config/redis/CacheConfig.java
  src/main/java/com/core/book/common/config/redis/RedisConfig.java
  src/main/java/com/core/book/common/exception/UnauthorizedException.java
  src/main/java/com/core/book/common/response/ErrorStatus.java
  src/main/java/com/core/book/common/response/SuccessStatus.java
Labels: FIX, 태근

#47 [FEAT] 다른 사용자 정보 불러오는 기능 구현
  src/main/java/com/core/book/api/member/controller/MemberController.java
  src/main/java/com/core/book/api/member/dto/OtherUserInfoResponseDTO.java
  src/main/java/com/core/book/api/member/service/MemberService.java
  src/main/java/com/core/book/common/exception/UnauthorizedException.java
  src/main/java/com/core/book/common/response/ErrorStatus.java
Labels: FEAT, 태근

#62 [FIX] 로그인 성공 리다이렉트 URL 포트 수정
  src/main/java/com/core/book/api/member/oauth2/handler/OAuth2LoginSuccessHandler.java
Labels: FIX, 태근

#64 [FIX] 테스트 도메인 JWT 토큰 생성 로직 수정
  src/main/java/com/core/book/api/member/jwt/filter/JwtAuthenticationProcessingFilter.java
  src/main/java/com/core/book/api/member/jwt/service/JwtService.java
  src/main/java/com/core/book/api/member/oauth2/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/core/book/api/member/service/MemberService.java
Labels: FIX, 태근

#66 [FIX] JWT 토큰 전달 방식 변경
  src/main/java/com/core/book/api/member/oauth2/handler/OAuth2LoginSuccessHandler.java
Labels: FIX, 태근

#68 [FIX] 카카오 OAuth2.0 로그인 로직 수정
  src/main/java/com/core/book/api/member/controller/MemberController.java
  src/main/java/com/core/book/api/member/dto/KakaoLoginRequestDTO.java
  src/main/java/com/core/book/api/member/dto/KakaoUserInfoDTO.java
  src/main/java/com/core/book/api/member/jwt/filter/JwtAuthenticationProcessingFilter.java
  src/main/java/com/core/book/api/member/jwt/service/JwtService.java
  src/main/java/com/core/book/api/member/oauth2/CustomOAuth2User.java
  src/main/java/com/core/book/api/member/oauth2/OAuthAttributes.java
  src/main/java/com/core/book/api/member/oauth2/handler/OAuth2LoginFailureHandler.java
  src/main/java/com/core/book/api/member/oauth2/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/core/book/api/member/oauth2/userinfo/KakaoOAuth2UserInfo.java
  src/main/java/com/core/book/api/member/oauth2/userinfo/OAuth2UserInfo.java
  src/main/java/com/core/book/api/member/service/MemberService.java
  src/main/java/com/core/book/api/member/service/OAuthService.java
  src/main/java/com/core/book/common/config/SecurityConfig.java
  src/main/java/com/core/book/common/config/oauth2/OAuth2Config.java
  src/main/java/com/core/book/common/config/swagger/SwaggerConfig.java
  src/main/java/com/core/book/common/response/ErrorStatus.java
  src/main/java/com/core/book/common/response/SuccessStatus.java
Labels: FIX, 태근

#72 [FIX] 스웨거 누락 정보 추가 및 수정, 정보공개 필드 카멜케이스 변경
  src/main/java/com/core/book/api/member/controller/MemberController.java
  src/main/java/com/core/book/api/member/dto/InfoOpenRequestDTO.java
  src/main/java/com/core/book/api/member/dto/UserInfoResponseDTO.java
  src/main/java/com/core/book/api/member/entity/InfoOpen.java
  src/main/java/com/core/book/api/member/service/MemberService.java
  src/main/java/com/core/book/common/config/swagger/SwaggerConfig.java
Labels: FIX, 태근

#76 [FIX] 팔로워 중 해당 유저 팔로잉 여부 체크 기능 구현
  src/main/java/com/core/book/api/member/dto/FollowedUserDTO.java
  src/main/java/com/core/book/api/member/dto/FollowerUserDTO.java
  src/main/java/com/core/book/api/member/repository/FollowRepository.java
  src/main/java/com/core/book/api/member/service/MemberService.java
Labels: FIX, 태근

#58 [FEAT] 책장(읽은 책/읽고 싶은 책) 기능 구현
  src/main/java/com/core/book/api/book/controller/BookController.java
  src/main/java/com/core/book/api/book/dto/BookDTO.java
  src/main/java/com/core/book/api/book/dto/ResultDTO.java
  src/main/java/com/core/book/api/book/entity/Book.java
  src/main/java/com/core/book/api/book/repository/BookRepository.java
  src/main/java/com/core/book/api/book/service/BookService.java
  src/main/java/com/core/book/api/bookshelf/controller/BookshelfController.java
  src/main/java/com/core/book/api/bookshelf/dto/ReadBooksDTO.java
  src/main/java/com/core/book/api/bookshelf/dto/ReadBookshelfRequestDTO.java
  src/main/java/com/core/book/api/bookshelf/dto/ReadBookshelfResponseDTO.java
  src/main/java/com/core/book/api/bookshelf/dto/WishBooksDTO.java
  src/main/java/com/core/book/api/bookshelf/dto/WishBookshelfRequestDTO.java
  src/main/java/com/core/book/api/bookshelf/dto/WishBookshelfResponseDTO.java
  src/main/java/com/core/book/api/bookshelf/entity/ReadBooks.java
  src/main/java/com/core/book/api/bookshelf/entity/ReadBooksTag.java
  src/main/java/com/core/book/api/bookshelf/entity/WishBooks.java
  src/main/java/com/core/book/api/bookshelf/repository/ReadBooksRepository.java
  src/main/java/com/core/book/api/bookshelf/repository/ReadBooksTagRepository.java
  src/main/java/com/core/book/api/bookshelf/repository/WishBooksRepository.java
  src/main/java/com/core/book/api/bookshelf/service/BookShelfService.java
  src/main/java/com/core/book/common/response/ErrorStatus.java
  src/main/java/com/core/book/common/response/SuccessStatus.java
Labels: FEAT, 주현

#80 [FIX] 스프링시큐리티 CORS ExposedHeader 설정
  src/main/java/com/core/book/common/config/SecurityConfig.java
Labels: FIX, 태근

#82 [FEAT] 책장 전체/월별 책 권수 데이터 제공 기능 구현
  src/main/java/com/core/book/api/book/service/BookService.java
  src/main/java/com/core/book/api/bookshelf/controller/BookshelfController.java
  src/main/java/com/core/book/api/bookshelf/dto/ReadBookshelfResponseDTO.java
  src/main/java/com/core/book/api/bookshelf/dto/WishBookshelfResponseDTO.java
  src/main/java/com/core/book/api/bookshelf/repository/ReadBooksRepository.java
  src/main/java/com/core/book/api/bookshelf/service/BookShelfService.java
Labels: FEAT, 주현

#85 [FIX] Bookshelf API Response Body 의 Key(키/필드) 이름 수정
  src/main/java/com/core/book/api/bookshelf/controller/BookshelfController.java
  src/main/java/com/core/book/api/bookshelf/dto/ReadBooksDTO.java
  src/main/java/com/core/book/api/bookshelf/dto/ReadBookshelfRequestDTO.java
  src/main/java/com/core/book/api/bookshelf/dto/WishBookshelfRequestDTO.java
  src/main/java/com/core/book/api/bookshelf/service/BookShelfService.java
Labels: FIX, 주현

#87 [FIX] Bookshelf Service 코드 내 DTO 변수 이름 수정
  src/main/java/com/core/book/api/bookshelf/service/BookShelfService.java
Labels: FIX, 주현

#89 [FIX] 책장 전체 조회 API 누락 데이터 및 응답 데이터 구성 수정
  src/main/java/com/core/book/api/bookshelf/controller/BookshelfController.java
  src/main/java/com/core/book/api/bookshelf/dto/ReadBookshelfResponseDTO.java
  src/main/java/com/core/book/api/bookshelf/dto/WishBookshelfResponseDTO.java
  src/main/java/com/core/book/api/bookshelf/service/BookShelfService.java
Labels: FIX, 주현
