Repository Moongeul/Backend, pull requests merged in 2024-10, with the labels that each got.

#92 [FEAT] 책장 전체 조회 페이징 처리 기능 구현
  src/main/java/com/core/book/api/bookshelf/controller/BookshelfController.java
  src/main/java/com/core/book/api/bookshelf/dto/ReadBookshelfResponseDTO.java
  src/main/java/com/core/book/api/bookshelf/dto/WishBookshelfResponseDTO.java
  src/main/java/com/core/book/api/bookshelf/repository/ReadBooksRepository.java
  src/main/java/com/core/book/api/bookshelf/repository/WishBooksRepository.java
  src/main/java/com/core/book/api/bookshelf/service/BookShelfService.java
Labels: FEAT, 주현

#93 [FEAT] 감상평 게시글 생성, 조회, 수정, 삭제 기능 구현
  src/main/java/com/core/book/api/article/controller/ArticleCreateController.java
  src/main/java/com/core/book/api/article/controller/ArticleDeleteController.java
  src/main/java/com/core/book/api/article/controller/ArticleModifyController.java
  src/main/java/com/core/book/api/article/controller/ArticleViewController.java
  src/main/java/com/core/book/api/article/dto/ReviewArticleCreateDTO.java
  src/main/java/com/core/book/api/article/dto/ReviewArticleDetailDTO.java
  src/main/java/com/core/book/api/article/dto/ReviewArticleListDTO.java
  src/main/java/com/core/book/api/article/dto/ReviewArticleListResponseDTO.java
  src/main/java/com/core/book/api/article/dto/ReviewArticleTagDTO.java
  src/main/java/com/core/book/api/article/entity/ArticleType.java
  src/main/java/com/core/book/api/article/entity/ReviewArticle.java
  src/main/java/com/core/book/api/article/entity/ReviewArticleTag.java
  src/main/java/com/core/book/api/article/repository/ReviewArticleRepository.java
  src/main/java/com/core/book/api/article/repository/ReviewArticleTagRepository.java
  src/main/java/com/core/book/api/article/service/ArticleCreateService.java
  src/main/java/com/core/book/api/article/service/ArticleDeleteService.java
  src/main/java/com/core/book/api/article/service/ArticleModifyService.java
  src/main/java/com/core/book/api/article/service/ArticleViewService.java
  src/main/java/com/core/book/api/member/entity/Member.java
  src/main/java/com/core/book/api/member/repository/FollowRepository.java
  src/main/java/com/core/book/common/response/ErrorStatus.java
  src/main/java/com/core/book/common/response/SuccessStatus.java
Labels: FEAT, 태근

#97 [FIX] 책장 코드 충돌 문제 해결
  src/main/java/com/core/book/api/bookshelf/repository/ReadBooksRepository.java
  src/main/java/com/core/book/api/bookshelf/repository/WishBooksRepository.java
Labels: FIX, 태근

#101 [FIX] 도서 API 요청 결과 XML 형식으로 수정 및 응답 형식 수정
  src/main/java/com/core/book/api/article/service/ArticleViewService.java
  src/main/java/com/core/book/api/book/controller/BookController.java
  src/main/java/com/core/book/api/book/dto/ResultDTO.java
  src/main/java/com/core/book/api/book/entity/Book.java
  src/main/java/com/core/book/api/book/service/BookService.java
  src/main/java/com/core/book/api/bookshelf/service/BookShelfService.java
Labels: FIX, 주현

#103 [FIX] build.gradle 에 Jackson XML 데이터 형식 라이브러리 추가
  build.gradle
Labels: FIX, 주현

#104 [FIX] 누락된 DTO 파일로 인한 BOOK 코드 충돌 문제 해결
  src/main/java/com/core/book/api/book/dto/BookDTO.java
  src/main/java/com/core/book/api/book/dto/BookResponseDTO.java
  src/main/java/com/core/book/api/book/dto/ChannelDTO.java
Labels: FIX, 주현

#107 [FIX] 책장 전체 조회 API 응답에 page 데이터 추가
  src/main/java/com/core/book/api/bookshelf/dto/ReadBookshelfResponseDTO.java
  src/main/java/com/core/book/api/bookshelf/dto/WishBookshelfResponseDTO.java
  src/main/java/com/core/book/api/bookshelf/service/BookShelfService.java
Labels: FIX, 주현

#108 [FEAT] 책 정보 자세히보기 API 단일 책 정보 가져오기 기능 구현
  src/main/java/com/core/book/api/book/controller/BookController.java
  src/main/java/com/core/book/api/book/dto/BookInfoDTO.java
  src/main/java/com/core/book/api/book/service/BookService.java
  src/main/java/com/core/book/common/response/ErrorStatus.java
  src/main/java/com/core/book/common/response/SuccessStatus.java
Labels: FEAT, 주현

#113 [FIX] 게시글 엔티티 추상클래스 변환
  src/main/java/com/core/book/api/article/entity/Article.java
  src/main/java/com/core/book/api/article/entity/ReviewArticle.java
  src/main/java/com/core/book/api/article/repository/ArticleRepository.java
  src/main/java/com/core/book/common/entity/BaseTimeEntity.java
Labels: FIX, 태근
